### ISSUE TITLE
Static location-based breadcrumb support

### ISSUE THREAD

**Issue by asliwinski** [MrLeebo/redux-breadcrumb-trail#5] opened 2017-06-23 14:21 UTC
Hi,

Thanks for adding support for the previous issue, though I haven't tested the functionality yet (will update in case of problems).

I have another concern, let me describe it using your example app. Say I follow the navigation path:
Products > Lemonade > Kansas City

The resulting breadcrumb is:

> (Home icon) > Products > Lemonade  0.05 > Kansas City, MO

Now, when I refresh the browser or go directly to "Kansas" (possible in my app) the breadcrumb results in:

> (Home icon) > Kansas City, MO

Would it be possible to maintain the fixed breadcrumb path (assuming I'm passing the full absolute path as a location):

> (Home icon) > Products > Lemonade  0.05 > Kansas City, MO

?

I'm actually not interested in the "trail functionality", which kind of defeats the purpose of using your package, however supporting the static option would make it more general and also render the existing packages (such as previously referenced react-breadcrumbs) obsolete.

**Comment by MrLeebo** [comment] 2017-06-23 14:51
@asliwinski That is by design, since the goal of this package is to have the breadcrumb represent your "trail" through the app. The breadcrumb state is in redux, which is just javascript. So as soon as you refresh the browser, the state is gone. Fortunately, redux has middleware such as https://github.com/rt2zz/redux-persist persist your redux state to local storage or a database. That middleware will work with redux-breadcrumb-trail.

Also related is #3 which is about adding an action creator to be able to reset the breadcrumb to an arbitrary path. If you don't want full redux persistence and only want a static path for a specific purpose, you could dispatch a reset action when you mount the component:

This is just an example, since the reset-to-static feature isn't implemented yet.
```jsx
import { reset } from 'redux-breadcrumb-trail'

// export default connect(null, mapDispatchToProps)(LocationComponent)
export function mapDispatchToProps(dispatch) {
  return bindActionCreators({
    resetToStatic: () => reset([
      { component: 'Home', url: '/' }, 
      { component: 'Products', url: '/products' }, 
      { component: 'Lemonade', url: '/products/1' }, 
      { component: 'Kansas City, MO', url: '/locations/1' }
    ])
  }, dispatch)
}

// Within LocationComponent
componentDidMount() {
  this.props.resetToStatic()
}
```

**Comment by MrLeebo** [comment] 2017-06-23 15:07
> Now, when I refresh the browser or go directly to "Kansas" (possible in my app) the breadcrumb results in:
> > (Home icon) > Kansas City, MO

If that happens in your app, you are probably triggering a full page refresh which you don't need.

Make sure when you have links in your app, such as a link to "Kansas" that you are using `react-router` `<Link>` components and not plain old `<a>` tags. Or if you are changing the route programmatically, that you are doing `router.push('/newroute')` and not `window.location = '/newroute'`. Not only will this preserve your breadcrumb trail, but performance will be much better because you won't be downloading all of the site's assets (CSS/JS/etc) again.

**Comment by asliwinski** [comment] 2017-06-23 15:14
I'm rather thinking about the case when you hit F5 for some reason, or, more commonly, share the link to a particular page with someone.

**Comment by MrLeebo** [comment] 2017-06-23 16:54
Sharing links is an interesting use-case I hadn't thought about.

If you compare the [react-router v4 recursive paths example](https://reacttraining.com/react-router/web/example/recursive-paths) to [the same example in redux-breadcrumb-trail](https://mrleebo.github.io/redux-breadcrumb-trail/#/friends/0), the key difference is that the RRv4 example saves the breadcrumb history in the URL. You need to do that to have shared links keep the breadcrumbs. 

I will try to get #3 implemented this weekend, now that I have a solid example of why it would be useful. Then you could read the route when the app starts, parse the breadcrumbs, and load your redux state to match the URL.

**Comment by MrLeebo** [comment] 2017-06-26 04:17
I realize that I suggested using redux-persist, but that wouldn't work because there was the option to keep react components stored in the redux store as breadcrumb items. 

I implemented a new release featuring [componentCache](/MrLeebo/redux-breadcrumb-trail/blob/master/docs/ComponentCache.md) which lets you match non-serializable breadcrumb components with serializable string names.

Between componentCache, redux-persist, and access to [redux-breadcrumb-trail's action creators](/MrLeebo/redux-breadcrumb-trail/blob/master/README.md), you should have all the tools you need to save the breadcrumb state, serialize it, and restore it when sharing a link or refreshing the page.

**Comment by MrLeebo** [comment] 2017-06-28 21:31
Closing this based on the proposed resolution in my previous comment.

**Closed as completed by MrLeebo** 2017-06-28 21:31 UTC
Labels: enhancement
