### ISSUE TITLE
Possible state mutation

### ISSUE THREAD

**Issue by asliwinski** [MrLeebo/redux-breadcrumb-trail#6] opened 2017-06-23 14:57 UTC
I'm using https://github.com/leoasis/redux-immutable-state-invariant to enforce state immutability.

In my app it throws the following:

> Uncaught Error: A state mutation was detected inside a dispatch, in the path: `breadcrumb.breadcrumbs.0.current`. Take a look at the reducer(s) handling the action {"type":"@@redux-breadcrumb-trail/PUSH","payload":{"location":{"pathname":"/workshops/workshop-title","search":"","hash":"","action":"PUSH","key":"czh5pe","query":{}},"params":{},"routes":[{"path":"/","breadcrumb":{"type":"i","key":null,"ref":null,"props":{"className":"fa fa-home"},"_owner":null,"_store":{}},"indexRoute":{"name":"Workshops","breadcrumb":"Workshops"},"childRoutes":[{"name":"Workshops","path":"workshops","breadcrumb":"Workshops"},{"name":"Workshop title","path":"workshops/workshop-title","ignoreParams":true,"breadcrumb":"Workshop title"},{"name":"Enrollment form","path":"workshops/workshop-title/enrollment-form","ignoreParams":true,"breadcrumb":"Enrollment form"},{"name":"Thanks","path":"workshops/workshop-title/enrollment-form/thanks","ignoreParams":true,"breadcrumb":"Thanks"}]},{"name":"Workshop title","path":"workshops/workshop-title","ignoreParams":true,"breadcrumb":"Workshop title"}]}}. (http://redux.js.org/docs/Troubleshooting.html#never-mutate-reducer-arguments)

My routes:

```
<Route path="/" component={App} breadcrumb={<i className="fa fa-home" />} >
        <IndexRoute name="Workshops" component={HomePage} breadcrumb="Workshops" />
        <Route name="Workshops" path="workshops" component={HomePage} breadcrumb="Workshops" />
        <Route name="Workshop title" path="workshops/workshop-title" component={WorkshopPage} ignoreParams breadcrumb="Workshop title"/>
        <Route name="Enrollment form" path="workshops/workshop-title/enrollment-form" component={WorkshopEnrollPage} ignoreParams breadcrumb="Enrollment form"/>
        <Route name="Thanks" path="workshops/workshop-title/enrollment-form/thanks" component={WorkshopEnrollThanksPage} ignoreParams breadcrumb="Thanks"/>
</Route>
```

In order to reproduce the issue I added this middleware to your example app.

store.js:
```
import { applyMiddleware, createStore, combineReducers } from 'redux'
import reduxImmutableStateInvariant from 'redux-immutable-state-invariant'

import fetch from './fetchReducer'
import breadcrumb from '../../../dist/reducer'

const rootReducer = combineReducers({ breadcrumb, fetch })
export default createStore(rootReducer,applyMiddleware(reduxImmutableStateInvariant()))
```

This time I'm only getting:

> Uncaught RangeError: Maximum call stack size exceeded
>     at trackProperties (trackForMutations.js:16)

I'm fairly new to redux, please let me know if I can debug this further or provide any more info.

**Comment by MrLeebo** [comment] 2017-06-23 16:55
Thanks for mentioning this, I will take a look.

**Comment by MrLeebo** [comment] 2017-06-25 06:51
@asliwinski Since it's not your app's responsibility to validate redux-breadcrumb-trail, you can fix the issue on your end by ignoring the breadcrumb state:

```js
const stateInvariantMiddleware = reduxImmutableStateInvariant({ ignore: ['breadcrumb'] })
```

That should be enough to fix the issue in your app. 

I want to talk a little bit about what's going on with the rest of the errors, so you don't have to read any further unless you're curious about the details surrounding this issue.

I can reproduce the error from your app in the example site using this middleware option:

```js
const stateInvariantMiddleware = reduxImmutableStateInvariant({ ignore: ['breadcrumb.breadcrumbs.0.component'] })
```

Could probably also get there by redefining the `isImmutable` function to do everything its already doing plus returning true for react nodes. I didn't test this though.

redux-immutable-state-invariant expects the redux store to be immutable and serializable. The `component` route prop can be a React Component, which has cyclical references and is non-serializable. **They are incompatible. I can't have it both ways.** 

I'm leaning towards putting a `won't fix` label on this issue and closing it, but I want to sleep on the problem and see if any other solutions come to me.

**Comment by MrLeebo** [comment] 2017-06-28 21:30
Looks like the state is modified so that `breadcrumbify` can re-render the active breadcrumb without receiving any other state changes (in case you've already reset your AJAX state for a new page). There probably is a better way to organize that code, but I don't think it's an issue. Feel free to submit a PR, though.

**Closed as completed by MrLeebo** 2017-06-28 21:30 UTC
Labels: wontfix
